version: "3.9"
    
services:
  python3.9:
    build: 
      context: .
      dockerfile: python3.9-Dockerfile
    image: ubuntu20.04:python3.9    
    volumes:
      - /Users/sachinkoli/my-secrets:/my-secrets
    environment:
      GIT_SRC: git@github.com:kolisachint/rest-api-example.git

# docker-compose -f python3.9-DockerCompose.yml up 